
GET http://localhost:8080/api/credential/student/requirements
###

POST http://localhost:8080/api/challenge
Content-Type: application/json

{
   "did": "did:iota:dev:DvSQ2o5hUHHPyekwAVtAeRkrBhW2hyhWF2swckwuvhno"
}
###

POST http://localhost:8080/api/credential/student/issue
Content-Type: application/json

{
    "@context": "https://www.w3.org/2018/credentials/v1",
    "type": "VerifiablePresentation",
    "verifiableCredential": {
        "@context": "https://www.w3.org/2018/credentials/v1",
        "type": [
            "VerifiableCredential",
            "NationalIDCredential"
        ],
        "credentialSubject": {
            "id": "did:iota:dev:DvSQ2o5hUHHPyekwAVtAeRkrBhW2hyhWF2swckwuvhno",
            "address": {
                "city": "Tjørvåg",
                "country": "Norway",
                "houseNumber": 1067,
                "postalCode": "3941",
                "state": "Trøndelag",
                "street": "Korsvollbakken"
            },
            "biometricPhotoURI": "https://thispersondoesnotexist.com",
            "dateOfBirth": "15/09/1955",
            "firstNames": [
                "Sophia"
            ],
            "lastName": "Skålevik",
            "nationality": "NO",
            "placeOfBirth": "Tjørvåg"
        },
        "issuer": "did:iota:dev:2UDYnryBpZyR1qbTKhz2FNTdfqXUdC4g7Z1mpHDKsz5G",
        "issuanceDate": "2023-06-11T11:55:45Z",
        "expirationDate": "2033-06-11T11:55:45Z",
        "nonTransferable": true,
        "proof": {
            "type": "JcsEd25519Signature2020",
            "verificationMethod": "did:iota:dev:2UDYnryBpZyR1qbTKhz2FNTdfqXUdC4g7Z1mpHDKsz5G#sign-0",
            "signatureValue": "4PKrgiwvBYGD4NQNgincwTgq4QVjyDkvyPjmhs5J2nWuMXvXjkpSZ3N1FLTmvUbDbPYAyZw6zcNsxCYtTVfUaF7b",
            "proofPurpose": "assertionMethod"
        }
    },
    "holder": "did:iota:dev:DvSQ2o5hUHHPyekwAVtAeRkrBhW2hyhWF2swckwuvhno",
    "proof": {
        "type": "JcsEd25519Signature2020",
        "verificationMethod": "did:iota:dev:DvSQ2o5hUHHPyekwAVtAeRkrBhW2hyhWF2swckwuvhno#sign-0",
        "signatureValue": "3tn4ZiNc3p8EPfrf2EmfQrEYejAcQRsMUVRX2jFYCUnoefQSvmj6dVrw5czNnsHbPpF7kttmo9SKV7NLGTcQ4sF8",
        "expires": "2023-06-13T20:46:00Z",
        "challenge": "4994ca8b6dcc81e4c8bd53d0d3b8f707bbba4cc29e6531acab511fc8d02eb122b"
    }
}
###
