# Server Config
@port = 8081
@host = localhost
# Student Identity
@username = heisenberg58
@password = ?!chemistry%Heck&Yeah420
@jwtToken = accessToken=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE2ODQ2NTQ1OTAsImV4cCI6MTY4NDY1NjM5MCwiYXVkIjoia2VlcGVyQERlbGwtMlZCOVI3MyIsImlzcyI6ImtlZXBlckBEZWxsLTJWQjlSNzMiLCJzdWIiOiJoZWlzZW5iZXJnNTgifQ.Rh18VHeMOT6bMZM7NBKkP3JFFMvG8-68qLWDe_g4I3I
@credentialName = walter


POST http://{{host}}:{{port}}/api/v0/auth/token/create
Content-Type: application/json

{
  "username": "{{username}}",
  "password": "{{password}}"
}
###

GET http://{{host}}:{{port}}/api/v0/auth/token/verify
Cookie: {{jwtToken}}
###

PUT http://{{host}}:{{port}}/api/v0/did/create
Content-Type: application/json

{
  "username": "{{username}}",
  "password": "{{password}}"
}
###

POST http://{{host}}:{{port}}/api/v0/did/get
Cookie: {{jwtToken}}
Content-Type: application/json

{
  "password": "{{password}}"
}
###

PUT http://{{host}}:{{port}}/api/v0/credentials/store
Cookie: {{jwtToken}}
Content-Type: application/json

{
  "credentialName": "{{credentialName}}",
  "verifiableCredential": {
  "@context": "https://www.w3.org/2018/credentials/v1",
  "type": [
    "VerifiableCredential",
    "StudentCredential"
  ],
  "credentialSubject": {
      "id": "did:iota:dev:DS5Do6Sry4vPYPtpZbMcgXUk865hybcSKcmcF8dRhJbK",
      "currentTerm": 1,
      "matriculationNumber": 1674059055349,
      "providerName": "Example University of Applied Sciences",
      "studentData": {
        "address": {
          "city": "Albuquerque",
          "country": "USA",
          "county": "New Mexico",
          "houseNumber": 308,
          "postalCode": 87104,
          "street": "Negra Arroyo Lane"
        },
        "birthDate": "07.09.1958",
        "familyName": "White",
        "firstName": "Walter",
        "middleNames": "Hartwell",
        "photo": "https://vignette.wikia.nocookie.net/breakingbad/images/e/e7/BB-S5B-Walt-590.jpg/revision/latest?cb=20130928055404/"
      },
      "studySubject": {
        "degree": "Master of Science",
        "name": "Chemistry"
      }
    },
    "issuer": "did:iota:dev:3T5kxWs9w24U93VMaJgpr6fzJ6YacEsg8mdob7vcZ5oB",
    "issuanceDate": "2023-01-18T16:24:15Z",
    "expirationDate": "2023-04-01T00:00:00Z",
    "nonTransferable": true,
    "proof": {
      "type": "JcsEd25519Signature2020",
      "verificationMethod": "did:iota:dev:3T5kxWs9w24U93VMaJgpr6fzJ6YacEsg8mdob7vcZ5oB#key-sign-student",
      "signatureValue": "2CyrVdZtncXfDdRWrHzAx7ZVM247FQ5wxoaYSGtVa9RJEEDxJukehJxiTGKgG8zNXbW7ki44Pb8m9tFqC6eSBZec"
    }
  }
}
###

GET http://{{host}}:{{port}}/api/v0/credentials/list
Cookie: {{jwtToken}}
###

GET http://{{host}}:{{port}}/api/v0/credentials/get/{{credentialName}}
Cookie: {{jwtToken}}
###

POST http://{{host}}:{{port}}/api/v0/presentations/create
Cookie: {{jwtToken}}
Content-Type: application/json

{
  "password": "{{password}}",
  "credentialNames": ["{{credentialName}}"],
  "challenge": "This is a challenge."
}
###