@username = "heisenberg58"
@password = "?!chemistry%Heck&Yeah420"
@jwtToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IlBhdHJpY2siLCJpYXQiOjE2NzQwODQwMzQsImV4cCI6MTY3NDY4ODgzNH0.RKHeEvviXsujx82-IUGOjUa7LPG5vYdnelBAdCpvIlw
@credentialName = walter

PUT http://localhost:8081/api/did/create
Content-Type: application/json

{
  "username": {{username}},
  "password": {{password}}
}
###

POST http://localhost:8081/api/did/login
Content-Type: application/json

{
  "username": {{username}},
  "password": {{password}}
}
###

POST http://localhost:8081/api/did/get
Authorization: Bearer {{jwtToken}}
Content-Type: application/json

{
  "password": {{password}}
}
###

PUT http://localhost:8081/api/credentials/store
Authorization: Bearer {{jwtToken}}
Content-Type: application/json

{
  "credentialName": "{{credentialName}}",
  "verifiableCredential": {
  "@context": "https://www.w3.org/2018/credentials/v1",
  "type": [
    "VerifiableCredential",
    "StudentCredential"
  ],
  "credentialSubject": {
      "id": "did:iota:dev:DS5Do6Sry4vPYPtpZbMcgXUk865hybcSKcmcF8dRhJbK",
      "currentTerm": 1,
      "matriculationNumber": 1674059055349,
      "providerName": "Example University of Applied Sciences",
      "studentData": {
        "address": {
          "city": "Albuquerque",
          "country": "USA",
          "county": "New Mexico",
          "houseNumber": 308,
          "postalCode": 87104,
          "street": "Negra Arroyo Lane"
        },
        "birthDate": "07.09.1958",
        "familyName": "White",
        "firstName": "Walter",
        "middleNames": "Hartwell",
        "photo": "https://vignette.wikia.nocookie.net/breakingbad/images/e/e7/BB-S5B-Walt-590.jpg/revision/latest?cb=20130928055404/"
      },
      "studySubject": {
        "degree": "Master of Science",
        "name": "Chemistry"
      }
    },
    "issuer": "did:iota:dev:3T5kxWs9w24U93VMaJgpr6fzJ6YacEsg8mdob7vcZ5oB",
    "issuanceDate": "2023-01-18T16:24:15Z",
    "expirationDate": "2023-04-01T00:00:00Z",
    "nonTransferable": true,
    "proof": {
      "type": "JcsEd25519Signature2020",
      "verificationMethod": "did:iota:dev:3T5kxWs9w24U93VMaJgpr6fzJ6YacEsg8mdob7vcZ5oB#key-sign-student",
      "signatureValue": "2CyrVdZtncXfDdRWrHzAx7ZVM247FQ5wxoaYSGtVa9RJEEDxJukehJxiTGKgG8zNXbW7ki44Pb8m9tFqC6eSBZec"
    }
  }
}
###

GET http://localhost:8081/api/credentials/list
Authorization: Bearer {{jwtToken}}
###

GET http://localhost:8081/api/credentials/get/{{credentialName}}
Authorization: Bearer {{jwtToken}}
Content-Type: application/json
###

POST http://localhost:8081/api/presentations/create
Authorization: Bearer {{jwtToken}}
Content-Type: application/json

{
  "password": {{password}},
  "credentialName": "{{credentialName}}",
  "challenge": "This is a challenge."
}
###