import cfg from '../../config.js'
import {
  Account,
  AccountBuilder,
  CekAlgorithm,
  EncryptedData,
  EncryptionAlgorithm,
  Resolver
} from '@iota/identity-wasm/node/identity_wasm.js'


/**
 * A `DigitalID` represents an identity with its own {@link Document}.
 * It offers high-level access to the IOTA Tangle, and
 * it is able to store its own secret keys through the {@link Account} and {@link Storage} API respectively.
 */
export abstract class DigitalID {
  protected static readonly builder = new AccountBuilder(cfg.iota.accBuilder)
  protected static resolver: Resolver
  protected static readonly resolverBuilder = Resolver.builder().clientConfig({
    network: cfg.iota.network,
    primaryNode: cfg.iota.primaryNode
  })

  readonly account: Account

  protected constructor(account: Account) {
    this.account = account
    console.log(this.toString());

    // this.verifySelf() TODO can do when published to tangle
  }

  /**
   * Decrypt a message that has been signed with a public key from this ID.
   * @param encryptedMessage The signature of the message
   * @param encryptionAlgorithm The algorithm that was used to encrypt the message.
   * @param cekAlgorithm ??
   * @param keyFragment The fragment of the public key that was used to encrypt the message.
   * @returns 
   */
  async decryptMessage(
    encryptedMessage: EncryptedData,
    encryptionAlgorithm: EncryptionAlgorithm,
    cekAlgorithm: CekAlgorithm,
    keyFragment: string
  ) {
    return await this.account.decryptData(encryptedMessage, encryptionAlgorithm, cekAlgorithm, keyFragment)
  }

  /**
   * Serialize the {@link Document} of this {@link DigitalID} as a {@link JSON} object.
   */
  toJSON() {
    return this.account.document().toJSON()
  }

  /**
   * Return a `string` representation of this account.
   */
  toString(): string {
    return JSON.stringify(this.toJSON(), null, 2)
  }

  /**
   * Verify that the {@link Document}'s signature was generated by a valid method. Also verify its syntax.
   */
  verifySelf(): void {
    this.account.document().verifyDocument(this.account.document())
  }
}