# Student Identity
@username = heisenberg58
@password = ?!chemistry%Heck&Yeah420
@jwtToken = accessToken=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImhlaXNlbmJlcmc1OCIsImlhdCI6MTY4NzEwMDExMywiZXhwIjoxNjg3MTA3MzEzLCJhdWQiOiJrZWVwZXJAREVTS1RPUC03UjlCOUZDIiwiaXNzIjoia2VlcGVyQERFU0tUT1AtN1I5QjlGQyIsInN1YiI6ImRpZDppb3RhOmRldjpFY1RDeFR4Tm5MZ0N6RUpNVDRZNHA2WHo1Wllwc1BZdVA1MTRoUHROODZCbiJ9.lmNMd9Rr-ravsrgZqALyQCl0fG5vmnmJxfbSpRs7FQ8
@credentialName = walter


POST http://localhost:8081/api/auth/token/create
Content-Type: application/json

{
  "username": "{{username}}",
  "password": "{{password}}"
}
###

GET http://localhost:8081/api/auth/token/verify
Cookie: {{jwtToken}}
###

PUT http://localhost:8081/api/did/create
Content-Type: application/json

{
  "username": "{{username}}",
  "password": "{{password}}"
}
###

GET http://localhost:8081/api/did/get
Cookie: {{jwtToken}}
###

PUT http://localhost:8081/api/credential/store/{{credentialName}}
Cookie: {{jwtToken}}
Content-Type: application/json

{
  "password": "{{password}}",
  "verifiableCredential": {
    "@context": "https://www.w3.org/2018/credentials/v1",
    "type": [
      "VerifiableCredential",
      "StudentCredential"
    ],
    "credentialSubject": {
      "id": "did:iota:dev:DS5Do6Sry4vPYPtpZbMcgXUk865hybcSKcmcF8dRhJbK",
      "currentTerm": 1,
      "matriculationNumber": 1674059055349,
      "providerName": "Example University of Applied Sciences",
      "studentData": {
        "address": {
          "city": "Albuquerque",
          "country": "USA",
          "county": "New Mexico",
          "houseNumber": 308,
          "postalCode": 87104,
          "street": "Negra Arroyo Lane"
        },
        "birthDate": "07.09.1958",                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               
        "familyName": "White",
        "firstName": "Walter",
        "middleNames": "Hartwell",
        "photo": "https://vignette.wikia.nocookie.net/breakingbad/images/e/e7/BB-S5B-Walt-590.jpg/revision/latest?cb=20130928055404/"
      },
      "studySubject": {
        "degree": "Master of Science",
        "name": "Chemistry"
      }
    },
    "issuer": "did:iota:dev:3T5kxWs9w24U93VMaJgpr6fzJ6YacEsg8mdob7vcZ5oB",
    "issuanceDate": "2023-01-18T16:24:15Z",
    "expirationDate": "2023-04-01T00:00:00Z",
    "nonTransferable": true,
    "proof": {
      "type": "JcsEd25519Signature2020",
      "verificationMethod": "did:iota:dev:3T5kxWs9w24U93VMaJgpr6fzJ6YacEsg8mdob7vcZ5oB#key-sign-student",
      "signatureValue": "2CyrVdZtncXfDdRWrHzAx7ZVM247FQ5wxoaYSGtVa9RJEEDxJukehJxiTGKgG8zNXbW7ki44Pb8m9tFqC6eSBZec"
    }
  }
}
###

GET http://localhost:8081/api/credential/list
Cookie: {{jwtToken}}
###

POST http://localhost:8081/api/credential/get/{{credentialName}}
Cookie: {{jwtToken}}
Content-Type: application/json

{
  "password": "{{password}}"
}
###

POST http://localhost:8081/api/presentation/create
Cookie: {{jwtToken}}
Content-Type: application/json

{
  "password": "{{password}}",
  "credentialNames": ["{{credentialName}}"],
  "challenge": "This is a challenge."
}
###